chore(): export PluginBase type from @scheduler/calendar package
PluginBase type is implicitly used in the `@schedule-x/preact` package.
However, the `npm run build:dts` command of that package fails with:

```
src/use-calendar-app.tsx:4:17 - error TS4058: Return type of exported function has or is using name 'PluginBase' from external module "/schedule-x/preact/node_modules/@schedule-x/calendar/dist/core" but cannot be named.

4 export function useCalendarApp(config: CalendarConfig) {
                  ~~~~~~~~~~~~~~

Found 1 error in src/use-calendar-app.tsx:4
```

because of this failure, the exported types by `@scheduler-x/preact` are
incorrectly generated and this results in things like IDE or other
typesafety checks to fail (at consumer site).

exporting `PluginBase` type fixes the issue.